CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE USER parseruser WITH PASSWORD 'parserpassword';

CREATE DATABASE parserdb OWNER postgres;

\c parserdb;

GRANT USAGE ON SCHEMA public TO parseruser;
GRANT CREATE ON SCHEMA public TO parseruser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO parseruser;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO parseruser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO parseruser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO parseruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO parseruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO parseruser;