// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/parse_channel.proto

package parserv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                           // message type: text, media text_media...
	HtmlText      string                 `protobuf:"bytes,2,opt,name=html_text,json=htmlText,proto3" json:"html_text,omitempty"`                   // telegram message with all text formating
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                // internal channel ID
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`                                   // channel username without @
	TelegramMsgId int64                  `protobuf:"varint,5,opt,name=telegram_msg_id,json=telegramMsgId,proto3" json:"telegram_msg_id,omitempty"` // tg internal message id
	Date          int64                  `protobuf:"varint,6,opt,name=date,proto3" json:"date,omitempty"`                                          // UTC UNIX time of message was puplicated
	PhotoUrls     []string               `protobuf:"bytes,7,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`                // tg message media photo url WARNING! telegram media links expire
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protos_parse_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetHtmlText() string {
	if x != nil {
		return x.HtmlText
	}
	return ""
}

func (x *Message) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Message) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Message) GetTelegramMsgId() int64 {
	if x != nil {
		return x.TelegramMsgId
	}
	return 0
}

func (x *Message) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Message) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

type NewChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelID     string                 `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"` // internal channel ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`   // channel username
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewChannelRequest) Reset() {
	*x = NewChannelRequest{}
	mi := &file_protos_parse_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChannelRequest) ProtoMessage() {}

func (x *NewChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChannelRequest.ProtoReflect.Descriptor instead.
func (*NewChannelRequest) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{1}
}

func (x *NewChannelRequest) GetChannelID() string {
	if x != nil {
		return x.ChannelID
	}
	return ""
}

func (x *NewChannelRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NewChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                           // channel username
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                   // channel name
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                     // channel description
	MsgInterval   int32                  `protobuf:"varint,5,opt,name=msg_interval,json=msgInterval,proto3" json:"msg_interval,omitempty"` // medium interval between messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewChannelResponse) Reset() {
	*x = NewChannelResponse{}
	mi := &file_protos_parse_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChannelResponse) ProtoMessage() {}

func (x *NewChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChannelResponse.ProtoReflect.Descriptor instead.
func (*NewChannelResponse) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{2}
}

func (x *NewChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NewChannelResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NewChannelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewChannelResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewChannelResponse) GetMsgInterval() int32 {
	if x != nil {
		return x.MsgInterval
	}
	return 0
}

type ParseMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelID     string                 `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"` // channel ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`   // username without @
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseMessagesRequest) Reset() {
	*x = ParseMessagesRequest{}
	mi := &file_protos_parse_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseMessagesRequest) ProtoMessage() {}

func (x *ParseMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseMessagesRequest.ProtoReflect.Descriptor instead.
func (*ParseMessagesRequest) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{3}
}

func (x *ParseMessagesRequest) GetChannelID() string {
	if x != nil {
		return x.ChannelID
	}
	return ""
}

func (x *ParseMessagesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ParseMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MsgInterval   int32                  `protobuf:"varint,2,opt,name=msg_interval,json=msgInterval,proto3" json:"msg_interval,omitempty"` // medium interval between messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseMessagesResponse) Reset() {
	*x = ParseMessagesResponse{}
	mi := &file_protos_parse_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseMessagesResponse) ProtoMessage() {}

func (x *ParseMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseMessagesResponse.ProtoReflect.Descriptor instead.
func (*ParseMessagesResponse) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{4}
}

func (x *ParseMessagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseMessagesResponse) GetMsgInterval() int32 {
	if x != nil {
		return x.MsgInterval
	}
	return 0
}

type FiltersRawMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelID     string                 `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`               // channel ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                 // channel username without @
	TgMsgId       int64                  `protobuf:"varint,3,opt,name=tg_msg_id,json=tgMsgId,proto3" json:"tg_msg_id,omitempty"` // from tg message id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiltersRawMessages) Reset() {
	*x = FiltersRawMessages{}
	mi := &file_protos_parse_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiltersRawMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiltersRawMessages) ProtoMessage() {}

func (x *FiltersRawMessages) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiltersRawMessages.ProtoReflect.Descriptor instead.
func (*FiltersRawMessages) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{5}
}

func (x *FiltersRawMessages) GetChannelID() string {
	if x != nil {
		return x.ChannelID
	}
	return ""
}

func (x *FiltersRawMessages) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FiltersRawMessages) GetTgMsgId() int64 {
	if x != nil {
		return x.TgMsgId
	}
	return 0
}

// request to get messages from channels tg_msg_id
type NewsSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*FiltersRawMessages  `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsSourcesRequest) Reset() {
	*x = NewsSourcesRequest{}
	mi := &file_protos_parse_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsSourcesRequest) ProtoMessage() {}

func (x *NewsSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsSourcesRequest.ProtoReflect.Descriptor instead.
func (*NewsSourcesRequest) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{6}
}

func (x *NewsSourcesRequest) GetFilters() []*FiltersRawMessages {
	if x != nil {
		return x.Filters
	}
	return nil
}

type NewsSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsSourcesResponse) Reset() {
	*x = NewsSourcesResponse{}
	mi := &file_protos_parse_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsSourcesResponse) ProtoMessage() {}

func (x *NewsSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parse_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsSourcesResponse.ProtoReflect.Descriptor instead.
func (*NewsSourcesResponse) Descriptor() ([]byte, []int) {
	return file_protos_parse_channel_proto_rawDescGZIP(), []int{7}
}

func (x *NewsSourcesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NewsSourcesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_protos_parse_channel_proto protoreflect.FileDescriptor

const file_protos_parse_channel_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/parse_channel.proto\x12\ttg_parser\"\xd0\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\thtml_text\x18\x02 \x01(\tR\bhtmlText\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12&\n" +
	"\x0ftelegram_msg_id\x18\x05 \x01(\x03R\rtelegramMsgId\x12\x12\n" +
	"\x04date\x18\x06 \x01(\x03R\x04date\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\a \x03(\tR\tphotoUrls\"M\n" +
	"\x11NewChannelRequest\x12\x1c\n" +
	"\tchannelID\x18\x01 \x01(\tR\tchannelID\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xa3\x01\n" +
	"\x12NewChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fmsg_interval\x18\x05 \x01(\x05R\vmsgInterval\"P\n" +
	"\x14ParseMessagesRequest\x12\x1c\n" +
	"\tchannelID\x18\x01 \x01(\tR\tchannelID\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"T\n" +
	"\x15ParseMessagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fmsg_interval\x18\x02 \x01(\x05R\vmsgInterval\"j\n" +
	"\x12FiltersRawMessages\x12\x1c\n" +
	"\tchannelID\x18\x01 \x01(\tR\tchannelID\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\ttg_msg_id\x18\x03 \x01(\x03R\atgMsgId\"M\n" +
	"\x12NewsSourcesRequest\x127\n" +
	"\afilters\x18\x01 \x03(\v2\x1d.tg_parser.FiltersRawMessagesR\afilters\"_\n" +
	"\x13NewsSourcesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\bmessages\x18\x02 \x03(\v2\x12.tg_parser.MessageR\bmessages2\xfc\x01\n" +
	"\bTgParser\x12N\n" +
	"\x0fParseNewChannel\x12\x1c.tg_parser.NewChannelRequest\x1a\x1d.tg_parser.NewChannelResponse\x12R\n" +
	"\rParseMessages\x12\x1f.tg_parser.ParseMessagesRequest\x1a .tg_parser.ParseMessagesResponse\x12L\n" +
	"\vNewsSources\x12\x1d.tg_parser.NewsSourcesRequest\x1a\x1e.tg_parser.NewsSourcesResponseB\rZ\v./;parserv1b\x06proto3"

var (
	file_protos_parse_channel_proto_rawDescOnce sync.Once
	file_protos_parse_channel_proto_rawDescData []byte
)

func file_protos_parse_channel_proto_rawDescGZIP() []byte {
	file_protos_parse_channel_proto_rawDescOnce.Do(func() {
		file_protos_parse_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_parse_channel_proto_rawDesc), len(file_protos_parse_channel_proto_rawDesc)))
	})
	return file_protos_parse_channel_proto_rawDescData
}

var file_protos_parse_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_parse_channel_proto_goTypes = []any{
	(*Message)(nil),               // 0: tg_parser.Message
	(*NewChannelRequest)(nil),     // 1: tg_parser.NewChannelRequest
	(*NewChannelResponse)(nil),    // 2: tg_parser.NewChannelResponse
	(*ParseMessagesRequest)(nil),  // 3: tg_parser.ParseMessagesRequest
	(*ParseMessagesResponse)(nil), // 4: tg_parser.ParseMessagesResponse
	(*FiltersRawMessages)(nil),    // 5: tg_parser.FiltersRawMessages
	(*NewsSourcesRequest)(nil),    // 6: tg_parser.NewsSourcesRequest
	(*NewsSourcesResponse)(nil),   // 7: tg_parser.NewsSourcesResponse
}
var file_protos_parse_channel_proto_depIdxs = []int32{
	5, // 0: tg_parser.NewsSourcesRequest.filters:type_name -> tg_parser.FiltersRawMessages
	0, // 1: tg_parser.NewsSourcesResponse.messages:type_name -> tg_parser.Message
	1, // 2: tg_parser.TgParser.ParseNewChannel:input_type -> tg_parser.NewChannelRequest
	3, // 3: tg_parser.TgParser.ParseMessages:input_type -> tg_parser.ParseMessagesRequest
	6, // 4: tg_parser.TgParser.NewsSources:input_type -> tg_parser.NewsSourcesRequest
	2, // 5: tg_parser.TgParser.ParseNewChannel:output_type -> tg_parser.NewChannelResponse
	4, // 6: tg_parser.TgParser.ParseMessages:output_type -> tg_parser.ParseMessagesResponse
	7, // 7: tg_parser.TgParser.NewsSources:output_type -> tg_parser.NewsSourcesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_parse_channel_proto_init() }
func file_protos_parse_channel_proto_init() {
	if File_protos_parse_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_parse_channel_proto_rawDesc), len(file_protos_parse_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_parse_channel_proto_goTypes,
		DependencyIndexes: file_protos_parse_channel_proto_depIdxs,
		MessageInfos:      file_protos_parse_channel_proto_msgTypes,
	}.Build()
	File_protos_parse_channel_proto = out.File
	file_protos_parse_channel_proto_goTypes = nil
	file_protos_parse_channel_proto_depIdxs = nil
}
