// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: protos/parse_channel.proto

package parserv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TgParser_ParseNewChannel_FullMethodName    = "/tg_parser.TgParser/ParseNewChannel"
	TgParser_ParseMessages_FullMethodName      = "/tg_parser.TgParser/ParseMessages"
	TgParser_GetChennelMessages_FullMethodName = "/tg_parser.TgParser/GetChennelMessages"
)

// TgParserClient is the client API for TgParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgParserClient interface {
	// Send request parser to parse tg channel information
	ParseNewChannel(ctx context.Context, in *NewChannelRequest, opts ...grpc.CallOption) (*NewChannelResponse, error)
	// Send request parser to parse tg channel messages
	ParseMessages(ctx context.Context, in *ParseMessagesRequest, opts ...grpc.CallOption) (*ParseMessagesResponse, error)
	// Receive messages by channel channel id
	GetChennelMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
}

type tgParserClient struct {
	cc grpc.ClientConnInterface
}

func NewTgParserClient(cc grpc.ClientConnInterface) TgParserClient {
	return &tgParserClient{cc}
}

func (c *tgParserClient) ParseNewChannel(ctx context.Context, in *NewChannelRequest, opts ...grpc.CallOption) (*NewChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewChannelResponse)
	err := c.cc.Invoke(ctx, TgParser_ParseNewChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgParserClient) ParseMessages(ctx context.Context, in *ParseMessagesRequest, opts ...grpc.CallOption) (*ParseMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseMessagesResponse)
	err := c.cc.Invoke(ctx, TgParser_ParseMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgParserClient) GetChennelMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, TgParser_GetChennelMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgParserServer is the server API for TgParser service.
// All implementations must embed UnimplementedTgParserServer
// for forward compatibility.
type TgParserServer interface {
	// Send request parser to parse tg channel information
	ParseNewChannel(context.Context, *NewChannelRequest) (*NewChannelResponse, error)
	// Send request parser to parse tg channel messages
	ParseMessages(context.Context, *ParseMessagesRequest) (*ParseMessagesResponse, error)
	// Receive messages by channel channel id
	GetChennelMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	mustEmbedUnimplementedTgParserServer()
}

// UnimplementedTgParserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTgParserServer struct{}

func (UnimplementedTgParserServer) ParseNewChannel(context.Context, *NewChannelRequest) (*NewChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseNewChannel not implemented")
}
func (UnimplementedTgParserServer) ParseMessages(context.Context, *ParseMessagesRequest) (*ParseMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseMessages not implemented")
}
func (UnimplementedTgParserServer) GetChennelMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChennelMessages not implemented")
}
func (UnimplementedTgParserServer) mustEmbedUnimplementedTgParserServer() {}
func (UnimplementedTgParserServer) testEmbeddedByValue()                  {}

// UnsafeTgParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgParserServer will
// result in compilation errors.
type UnsafeTgParserServer interface {
	mustEmbedUnimplementedTgParserServer()
}

func RegisterTgParserServer(s grpc.ServiceRegistrar, srv TgParserServer) {
	// If the following call pancis, it indicates UnimplementedTgParserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TgParser_ServiceDesc, srv)
}

func _TgParser_ParseNewChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgParserServer).ParseNewChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgParser_ParseNewChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgParserServer).ParseNewChannel(ctx, req.(*NewChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgParser_ParseMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgParserServer).ParseMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgParser_ParseMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgParserServer).ParseMessages(ctx, req.(*ParseMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgParser_GetChennelMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgParserServer).GetChennelMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgParser_GetChennelMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgParserServer).GetChennelMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TgParser_ServiceDesc is the grpc.ServiceDesc for TgParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tg_parser.TgParser",
	HandlerType: (*TgParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseNewChannel",
			Handler:    _TgParser_ParseNewChannel_Handler,
		},
		{
			MethodName: "ParseMessages",
			Handler:    _TgParser_ParseMessages_Handler,
		},
		{
			MethodName: "GetChennelMessages",
			Handler:    _TgParser_GetChennelMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/parse_channel.proto",
}
